version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "gunicorn", "-b", "0.0.0.0:5000", "app:app"]

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: next_frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data: