"""Initial migration

Revision ID: 13fe2a663534
Revises: 
Create Date: 2025-03-07 22:30:11.593990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fe2a663534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
