"""Change updated_at to store only date

Revision ID: bdbffdf32fc5
Revises: 13fe2a663534
Create Date: 2025-03-07 23:18:39.137674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbffdf32fc5'
down_revision = '13fe2a663534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Date(), nullable=True))
        batch_op.alter_column('daily',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.alter_column('daily',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
